name: Deploy to EC2 via SSH

on:
  push:
    branches:
      - main
      - dev

env:
  EC2_PROJECT_DIR: /home/ec2-user/bloody-webapp/webapp
  DOCKER_COMPOSE_FILE: docker-compose.yml

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e
            cd ${{ env.EC2_PROJECT_DIR }}

            echo "Pulling latest code..."
            git pull

            echo "Stopping old containers..."
            sudo docker-compose down || true

            echo "Rebuilding and starting new containers..."
            sudo docker-compose up --build -d

            echo "Deployment complete ✅"

      - name: Verify deployment health
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "Checking if app is running..."
            curl -I http://localhost:3000 || curl -I http://localhost
